name: Deploy to Hostinger via FTPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v4

      - name: 📂 Deploy files to Hostinger via FTPS
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.HOSTINGER_FTPS_SERVER }}  # Use FTPS
          username: ${{ secrets.HOSTINGER_FTPS_USERNAME }}
          password: ${{ secrets.HOSTINGER_FTPS_PASSWORD }}
          protocol: ftps
          dry-run: true
          log-level: verbose
          exclude: |
          **/.git*
          **/.git*/**
          **/_PreAssets/**
          **/scss/**
          fileToExclude.txt